# ARTIFICIAL NEURAL NETWORKS

## PART 1: DATA PREPROCESSING

In [9]:
#importing libraries
import numpy as np
import pandas as pd
import tensorflow as tf

#tf.__version__

#Data Preprocessing


#Importing dataset, we have to observe which column do we need as our independent variable
dataset=pd.read_csv("E:\\MLPython\\Churn_Modelling.csv")
x=dataset.iloc[:, 3:-1].values
y=dataset.iloc[:,-1].values

#Lets check the values are perfectly separated
#print(x)
#print(y)

#Now we have to encode the string data, Gender column will be encoded by one hot encoding
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
x[:, 2]=le.fit_transform(x[:, 2])

#Again checking
#print(x)

#Geography column will be encoded by oneHotEncoding because it is categorical data
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct=ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])], remainder='passthrough')
x=np.array(ct.fit_transform(x))
print(x)

#Splitting dataset into training and test set
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test=train_test_split(x, y, test_size=0.3, random_state=0)

#Feature scaling is very important in deep learning to train and built efficient model
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
x_train=sc.fit_transform(x_train)
x_test=sc.transform(x_test)

[[1.0 0.0 0.0 ... 1 1 101348.88]
 [0.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 0.0 ... 1 0 38190.78]]


## PART 2: BUILDING THE ANN

In [12]:
#---------------------Initializing the Ann----------------#
#Initializing the ANN using keras
ann = tf.keras.models.Sequential()


#Adding input layer and first hidden layer
#units = number of neurons in input layer, should be equal to number of independent variables
#activation=Any appropriate Activationfunction(relu, sigmoid etc)
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))


#Adding second hidden layer
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))


#Adding the output layer
#(in output layer) units = dimensions of variable we have to predict
# Sigmoid would be better option for binary outcome
ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

## PART 3: TRAINING THE ANN

In [25]:
#--------------------------Compiling the ANN-----------------------#
#optimizer = any optimizer
#loss = loss function
#metrics
ann.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

#Training the ANN on training dataset
#fit method always use for training model, any model in ML/DL
#Batch_size = number of input row input to model at a time
ann.fit(x_train, y_train, batch_size=32, epochs=100)


Epoch 1/100
219/219 [==============================] - 0s 842us/step - loss: 0.3428 - accuracy: 0.8620
Epoch 2/100
219/219 [==============================] - 0s 840us/step - loss: 0.3420 - accuracy: 0.8623
Epoch 3/100
219/219 [==============================] - 0s 827us/step - loss: 0.3410 - accuracy: 0.8631
Epoch 4/100
219/219 [==============================] - 0s 832us/step - loss: 0.3409 - accuracy: 0.8611
Epoch 5/100
219/219 [==============================] - 0s 814us/step - loss: 0.3404 - accuracy: 0.8619
Epoch 6/100
219/219 [==============================] - 0s 796us/step - loss: 0.3400 - accuracy: 0.8616
Epoch 7/100
219/219 [==============================] - 0s 811us/step - loss: 0.3395 - accuracy: 0.8626
Epoch 8/100
219/219 [==============================] - 0s 797us/step - loss: 0.3390 - accuracy: 0.8634
Epoch 9/100
219/219 [==============================] - 0s 840us/step - loss: 0.3387 - accuracy: 0.8631
Epoch 10/100
219/219 [==============================] - 0s 864us/step - l

Epoch 80/100
219/219 [==============================] - 0s 826us/step - loss: 0.3319 - accuracy: 0.8633
Epoch 81/100
219/219 [==============================] - 0s 805us/step - loss: 0.3317 - accuracy: 0.8620
Epoch 82/100
219/219 [==============================] - 0s 787us/step - loss: 0.3315 - accuracy: 0.8634
Epoch 83/100
219/219 [==============================] - 0s 766us/step - loss: 0.3319 - accuracy: 0.8626
Epoch 84/100
219/219 [==============================] - 0s 801us/step - loss: 0.3314 - accuracy: 0.8621
Epoch 85/100
219/219 [==============================] - 0s 791us/step - loss: 0.3316 - accuracy: 0.8639
Epoch 86/100
219/219 [==============================] - 0s 734us/step - loss: 0.3311 - accuracy: 0.8641
Epoch 87/100
219/219 [==============================] - 0s 771us/step - loss: 0.3317 - accuracy: 0.8626
Epoch 88/100
219/219 [==============================] - 0s 767us/step - loss: 0.3315 - accuracy: 0.8624
Epoch 89/100
219/219 [==============================] - 0s 810us

## PART 4: MAKING THE PREDICTIONS AND EVALUATING THE MODELS

In [26]:
#Predicting the results
#predict using the following information
#Geography = France
#Credit score=600
#Gender = Male
#Age = 40 years
#Tenure = 3 year
#Balance = 60000
#Number of product = 2

#We need to scale the output, if we want to know the probability of output
ann.predict(sc.transform([[1, 0, 0, 600, 1, 40, 3, 60000, 2, 1, 1, 50000]]))

#If we want to get the actual result, simply give appropriate condition according to the threshold your have selected. In this case, it is 0.5
print(ann.predict(sc.transform([[1, 0, 0, 600, 1, 40, 3, 60000, 2, 1, 1, 50000]])) > 0.5)

[[False]]


## PREDICTING THE TEST SET RESULT

In [27]:
y_pred = ann.predict(x_test)
y_pred = (y_pred > 0.5)
print(np.concatenate((y_pred.reshape(len(y_pred), 1), y_test.reshape(len(y_test), 1)), 1))


#--------Finding the accuracy of ANN-------------#
from sklearn.metrics import confusion_matrix, accuracy_score
CM = confusion_matrix(y_test, y_pred)
Acc = accuracy_score(y_test, y_pred)

#Printing out results
print("Confusion matrix : \n", CM)
print("\nAccuracy : ", (Acc * 100))


[[0 0]
 [0 1]
 [0 0]
 ...
 [0 0]
 [0 0]
 [1 1]]
Confusion matrix : 
 [[2277  102]
 [ 316  305]]

Accuracy :  86.06666666666666
